### ISSUE TITLE
Crash on accessing missing index in `proto.IsIPv4`

### ISSUE THREAD

**Issue by simPod** [netsampler/goflow2#251]
**Describe the bug**

```
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: panic: runtime error: index out of range [0] with length 0
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: goroutine 152 [running]:
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.IsIPv4(...)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:211
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.ParseEthernetHeader(0xc0071a6d20, {0xc006d184b0, 0x40, 0x1e78}, 0x0)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:265 +0x1dbc
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.ParseSampledHeaderConfig(0x4?, 0x6?, 0x6?)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:384 +0x2d
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.SearchSFlowSampleConfig(0xc0071a6d20, {0xace180?, 0xc0032242d0?}, 0xc00511f908?)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:414 +0x75c
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.SearchSFlowSamplesConfig({0xc00304e280?, 0x6, 0xc00511f950?}, 0x4524e9?)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:473 +0xf4
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.ProcessMessageSFlowConfig(0x9f7360?, 0xc00511f860?)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/producer_sf.go:492 +0x273
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/producer/proto.(*ProtoProducer).Produce(0xc0001dc820, {0xa4f2e0?, 0xc002b77f40?}, 0xc00854f730)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/producer/proto/proto.go:73 +0x14e
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/metrics.(*PromProducerWrapper).Produce(0xa4f360?, {0xa4f2e0?, 0xc002b77f40?}, 0xc00854f730)
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/metrics/producer.go:20 +0x52
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/utils.(*SFlowPipe).DecodeFlow(0xc000296cc0, {0x9f6160?, 0xc00854f6c0})
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/utils/pipe.go:127 +0x306
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: main.main.PromDecoderWrapper.func5({0x9f6160?, 0xc00854f6c0?})
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/metrics/decoder.go:53 +0x63c
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: github.com/netsampler/goflow2/v2/utils.(*UDPReceiver).decoders.func1()
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/utils/udp.go:215 +0x249
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]: created by github.com/netsampler/goflow2/v2/utils.(*UDPReceiver).decoders in goroutine 1
Dec 06 12:30:42 flop-goflow-1 goflow2[2464383]:         /buildir/utils/udp.go:200 +0x32
Dec 06 12:30:42 flop-goflow-1 systemd[1]: goflow2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**To Reproduce**
1. Unfortunately I don't have the problematic packet captured yet.

**Expected behavior**
No crash

**Captures**
If applicable, add output (JSON, protobuf), packet captures and device configuration.

**Sampler device:**

N/A for now

 - Brand: [e.g. Cisco, Juniper, Arista, Mikrotik]
 - Model: [e.g. MX, QFX]
 - Version: [e.g. 22]
 - Estimated flow traffic: 32K

**GoFlow2:**
 - Version: v2

**Comment by lspgn** [comment]
Thank you for reporting, could you check if  https://github.com/netsampler/goflow2/pull/252 works for you?
